# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 20:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arandusite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandusite.Area')),
            ],
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LearningList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='learning_list/thumbnail')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandusite.Course')),
            ],
        ),
        migrations.CreateModel(
            name='LearningListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.IntegerField()),
                ('learning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandusite.LearningItem')),
                ('learning_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandusite.LearningList')),
            ],
        ),
        migrations.CreateModel(
            name='LearningVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('url', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandusite.LearningList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='learninglist',
            name='items',
            field=models.ManyToManyField(through='arandusite.LearningListItem', to='arandusite.LearningItem'),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
