# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arandusite', '0003_auto_20160416_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningvideo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='learningvideo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='learningvideo',
            name='user',
        ),
    ]
