# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arandusite', '0005_auto_20160416_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandusite.Skill')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arandusite.LearningVideo')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='area',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='description_pt_BR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='title',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='title_pt_BR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='skills',
            field=models.ManyToManyField(to='arandusite.Skill'),
        ),
    ]
