# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandusite', '0006_auto_20160416_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_pt_BR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_pt_BR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='description_pt_BR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='title',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learninglist',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learninglist',
            name='title_pt_BR',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
