# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandusite', '0007_auto_20160416_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='title',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
