# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arandusite', '0009_auto_20160416_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='description_pt_BR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='title_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='title_pt_BR',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
